[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vision_classifier"
version = "0.0.1"
authors = [
  { name="Durandnico", email="durandnico@duck.com" },
]
description = "A few-shot vision classifier package."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "Pillow",
]

[project.optional-dependencies]
hf = [
    "torch",
    "transformers",
]
ollama = [
    "ollama",
]

[project.urls]
